application:
  path:
    authors: data/autoren.csv
    books: data/buecher.csv
    magazines: data/zeitschriften.csv

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties.hibernate:
        format_sql: true